# Generated by Django 3.2.6 on 2021-08-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('especialidade', models.CharField(choices=[('F', 'Front-end'), ('B', 'Back-end'), ('I', 'Infraestrutura')], max_length=1)),
                ('idade', models.IntegerField(max_length=2)),
                ('sobre', models.TextField()),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('esta_devendo', models.BooleanField(default=True)),
                ('observacoes', models.TextField()),
            ],
        ),
    ]
