# Generated by Django 3.2.6 on 2021-08-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
